from __future__ import annotations

from typing import Any

from mcp.server.fastmcp import FastMCP

from b2b_next_basket_mcp.business_logic import make_sales_recommendation
from b2b_next_basket_mcp.inference import OrderPredictor
from b2b_next_basket_mcp.token_utils import (
    compact_token_preview,
    extract_time_prediction,
    readable_items_from_tokens,
    split_tokens,
)

mcp = FastMCP("b2b-next-basket-prediction")

# Load model/dataset once at server startup.
predictor = OrderPredictor()


@mcp.tool()
def list_clients(limit: int = 20) -> dict[str, Any]:
    """List available B2B client IDs in the local demo dataset."""
    if limit < 1 or limit > 200:
        raise ValueError("limit must be between 1 and 200.")
    clients = predictor.list_clients()
    return {
        "total_clients": len(clients),
        "clients": clients[:limit],
    }


@mcp.tool()
def get_sample_history(client_id: str) -> dict[str, Any]:
    """Return a compact summary of one sample historical order sequence."""
    history = predictor.get_sample_history(client_id)
    preview = compact_token_preview(history)
    return {
        "client_id": client_id,
        "total_tokens": preview["total_tokens"],
        "estimated_order_events": preview["estimated_order_events"],
        "preview_start": preview["preview_start"],
        "recent_history": preview["recent_history"],
        "full_history_available": False,
        "note": (
            "Sample history is intentionally compact for demos. "
            "Use the full raw sequence internally when passing history into prediction."
        ),
    }


@mcp.tool()
def get_prediction_input_sample(client_id: str) -> dict[str, Any]:
    """Return full raw history for dev/demo prediction input, not normal display output."""
    history = predictor.get_sample_history(client_id)
    return {
        "client_id": client_id,
        "start_text": history,
        "total_tokens": len(split_tokens(history)),
        "note": (
            "This full raw sequence exists only to seed prediction during local demos "
            "and development. Prefer get_sample_history for readable display output."
        ),
    }


@mcp.tool()
def predict_next_basket(
    client_id: str,
    start_text: str,
    max_generate: int = 30,
    temperature: float = 1.0,
    top_k: int = 20,
) -> dict[str, Any]:
    """Predict the next likely B2B order basket for a selected client."""
    result = predictor.predict_next_basket(
        client_id=client_id,
        start_text=start_text,
        max_generate=max_generate,
        temperature=temperature,
        top_k=top_k,
    )

    readable_items = readable_items_from_tokens(result["predicted_tokens"])
    time_prediction = extract_time_prediction(result["predicted_tokens"])

    return {
        **result,
        "time_prediction": time_prediction,
        "readable_items": readable_items,
        "note": "Prediction generated by local ONNX backend. This is not an automatic order.",
    }


@mcp.tool()
def recommend_next_action(
    client_id: str,
    start_text: str,
    max_generate: int = 30,
    temperature: float = 1.0,
    top_k: int = 20,
) -> dict[str, Any]:
    """Predict the next basket and convert it into a safe sales recommendation."""
    prediction = predict_next_basket(
        client_id=client_id,
        start_text=start_text,
        max_generate=max_generate,
        temperature=temperature,
        top_k=top_k,
    )

    recommendation = make_sales_recommendation(
        client_id=client_id,
        readable_items=prediction["readable_items"],
        time_prediction=prediction["time_prediction"],
    )

    return {
        "prediction": prediction,
        "recommendation": recommendation,
    }


@mcp.resource("b2b://model-card/next-basket-prediction")
def model_card() -> str:
    return """
    Model: B2B next-basket order prediction

    Purpose:
    Predict likely next products/items for a selected B2B client based on historical order-token sequences.

    Inputs:
    - client_id
    - historical order sequence
    - generation parameters such as top_k and temperature

    Outputs:
    - predicted product tokens
    - readable item names
    - optional timing token
    - safe sales recommendation

    Safety:
    - This server provides recommendation-only output.
    - It does not place orders.
    - It does not contact customers.
    - Human approval is required before business action.
    """


def main() -> None:
    mcp.run()


if __name__ == "__main__":
    main()
